name: PR Build Job

on:
 pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh
