name: Release Job

on:
  workflow_dispatch:
  push:
    tags:
    - '*.*.*'

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.303
    - name: Build and Test
      run: ./Build.ps1
      shell: pwsh
    - name: Push Mediate to NuGet
      env:
        NUGET_URL: https://api.nuget.org/v3/index.json
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        PROJECT_PATH: src/Mediate/Mediate.csproj
      run: ./Push.ps1
      shell: pwsh
    - name: Push Mediate.BackgroundEventDispatch to NuGet
      env:
        NUGET_URL: https://api.nuget.org/v3/index.json
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        PROJECT_PATH: src/Mediate.BackgroundEventDispatch/Mediate.BackgroundEventDispatch.csproj
      run: ./Push.ps1
      shell: pwsh
